#!/bin/sh

# Git file history as patch

[ -z "$1" ] && echo "$0 <file> - git file history" && exit 1

[ ! -r "$1" ] && echo "Can't read file $1" && exit 1

# target directory for work
# KAVGIT_TARGETDIR=$(pwd) # can be in ~/.kavgitutils
KAVGIT_TARGETDIR="/dev/shm"

[ -d "$HOME" ] && [ -f "$HOME/.kavgitutils" ] && source "$HOME/.kavgitutils"

TF="$(mktemp -u -p $KAVGIT_TARGETDIR).patch"
echo "Save history to $TF, wait some time..."
git log --follow -p -- $1 > $TF
if [ $? -eq 0 ]; then
	echo "Open file in editor..."
	mcedit $TF
else
	echo "Can't save history for $1"
fi

rm $TF
